const STORE = {
  phone: "923351295731",
  displayPhone: "+92 335 1295731",
  instagram: "https://www.instagram.com/vaelt.pk/"
};

const products = [
  {
    code:"VAELT-001",brand:"gandu",
   name:"ghulam chor",
   category:"running",
   price:"500",
   size:"6 foot",
   condition:"muthal",
   image:"images/Capture.PNG",
   gallery:["images/Capture.PNG"],
   description:"Preloved Nike running shoes in excellent condition. Clean upper with comfortable cushioning and good outsole grip.",
  },
  {
    code:"VAELT-002",
    brand:"nike",
    name:"Air Jrdan 31",
    category:"sneakers",
    price:3000,
    size:"UK 7",
    condition:"Very Good",
    image:"images/images (2).jfif",
    gallery:["images/images (2).jfif","images/14398178_21135409_1000.webp"],
    description:"Classic Adidas-inspired street sneaker listing. Replace the sample photos and details with your actual pair.",
  },
  {
    code:"VAELT-003",
    brand:"New Balance",
    name:"Daily Runner",
    category:"running",
    price:7200,
    size:"UK 10",
    condition:"Excellent",
    image:"images/images (2).jfif",
    gallery:["images/nike-af1.jpg","images/shoe-3-side.svg"],
    description:"Comfort-focused running pair with a lightweight feel. Add your own inspection notes here.",
  },
  {
    code:"VAELT-004",
    brand:"Vans",
    name:"Canvas Classic",
    category:"casual",
    price:4500,
    size:"UK 8",
    condition:"Good",
    image:"images/images (2).jfif",
    gallery:["images/shoe-4.svg","images/shoe-4-side.svg"],
    description:"Everyday casual pair. Update the condition and measurements with your actual product information.",
  },
  {
    code:"VAELT-005",
    brand:"Puma",
    name:"Court Low",
    category:"sneakers",
    price:5200,
    size:"UK 9",
    condition:"Very Good",
    image:"images/images (2).jfif",
    gallery:["images/shoe-5.svg","images/shoe-5-side.svg"],
    description:"Clean low-profile sneaker. Add exact model, material and authenticity evidence for your listing.",
  },
  {
    code:"VAELT-006",
    brand:"Leather Select",
    name:"Oxford Classic",
    category:"formal",
    price:6000,
    size:"UK 9",
    condition:"Excellent",
    image:"images/images (2).jfif",
    gallery:["images/shoe-6.svg","images/shoe-6-side.svg"],
    description:"Classic formal shoe listing. Replace this sample information with your actual pair.",
  },
  {
    code:"VAELT-007",
    brand:"Leather Select",
    name:"Oxford Classic",
    category:"sneakers",
    price:2000,
    size:"UK 9",
    condition:"Excellent",
    image:"images/images (2).jfif",
    gallery:["images/hd-aspect-1469062506-air-jordan-31.jpg","images/shoe-7-side.svg"],
    description:"Classic formal shoe listing. Replace this sample information with your actual pair.",
  }
];
