const money=n=>`Rs. ${Number(n).toLocaleString("en-PK")}`;
function setupContact(){document.querySelectorAll("#contactTop,#contactFooter").forEach(el=>{el.href=`https://wa.me/${STORE.phone}`})}
function productCard(p){return `<article class="card"><a href="product.html?code=${encodeURIComponent(p.code)}" class="card-image"><img src="${p.image}" alt="${p.brand} ${p.name}" loading="lazy"><span class="condition">${p.condition}</span></a><div class="card-info"><div><span class="brand">${p.brand}</span><span class="code">${p.code}</span></div><a href="product.html?code=${encodeURIComponent(p.code)}"><h3>${p.name}</h3></a><div class="meta"><span>${p.size}</span><strong>${money(p.price)}</strong></div></div></article>`}
function renderProducts(list=products){const g=document.getElementById("productsGrid");if(!g)return;g.innerHTML=list.length?list.map(productCard).join(""):`<div class="empty">No product found.</div>`;const c=document.getElementById("count");if(c)c.textContent=`${list.length} products`}
function findCode(code){return products.find(p=>p.code.toUpperCase()===(code||"").trim().toUpperCase())}
function setupCodeSearch(){const f=document.getElementById("codeForm");if(!f)return;f.addEventListener("submit",e=>{e.preventDefault();const term=document.getElementById("codeInput").value.trim(),msg=document.getElementById("searchMessage");if(!/^VAELT-\d+$/i.test(term)){msg.textContent="Enter a valid VAELT code, e.g. VAELT-001.";return}const p=findCode(term);if(p)location.href=`product.html?code=${encodeURIComponent(p.code)}`;else msg.textContent="No product matches that code."})}
function setupFilters(){document.querySelectorAll(".filter").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");const c=b.dataset.category;renderProducts(c==="all"?products:products.filter(p=>p.category===c))}))}
function renderProductPage(){const box=document.getElementById("productPage");if(!box)return;const p=findCode(new URLSearchParams(location.search).get("code"));if(!p){box.innerHTML=`<div class="not-found"><h1>Product not found</h1><p>Check the VAELT code.</p><a class="hero-btn" href="index.html#shop">BACK TO SHOP</a></div>`;return}const gallery=p.gallery?.length?p.gallery:[p.image],msg=`Hi VAELT 👋 I'm interested in ${p.brand} ${p.name}. Product Code: ${p.code}. Is it still available?`;box.innerHTML=`<div class="breadcrumbs"><a href="index.html">HOME</a> / <a href="index.html#shop">SHOP</a> / ${p.code}</div><div class="product-layout"><div class="gallery"><div class="main-photo"><img id="mainPhoto" src="${gallery[0]}" alt="${p.name}"></div><div class="thumbs">${gallery.map((img,i)=>`<button class="${i===0?"selected":""}" data-img="${img}"><img src="${img}" alt=""></button>`).join("")}</div></div><div class="product-info"><span>${p.brand} • ${p.code}</span><h1>${p.name}</h1><div class="big-price">${money(p.price)}</div><div class="specs"><div><span>SIZE</span><strong>${p.size}</strong></div><div><span>CONDITION</span><strong>${p.condition}</strong></div><div><span>CODE</span><strong>${p.code}</strong></div></div><p>${p.description}</p><div class="action-buttons"><a class="order-btn instagram-btn" href="${STORE.instagram}" target="_blank">ASK ON INSTAGRAM</a><a class="order-btn whatsapp-btn" href="https://wa.me/${STORE.phone}?text=${encodeURIComponent(msg)}" target="_blank">MESSAGE ON WHATSAPP</a></div><div class="product-note">Product code <strong>${p.code}</strong> is included in your WhatsApp message.</div></div></div>`;document.querySelectorAll(".thumbs button").forEach(b=>b.onclick=()=>{document.getElementById("mainPhoto").src=b.dataset.img;document.querySelectorAll(".thumbs button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")});document.title=`VAELT — ${p.brand} ${p.name}`}
function setupReturnPolicy(){const l=document.getElementById("returnPolicyLink"),m=document.getElementById("returnPolicyModal"),c=document.getElementById("returnPolicyClose");if(!l||!m)return;l.onclick=e=>{e.preventDefault();m.classList.add("open");m.setAttribute("aria-hidden","false")};c?.addEventListener("click",()=>m.classList.remove("open"));m.addEventListener("click",e=>{if(e.target===m)m.classList.remove("open")})}
setupContact();setupCodeSearch();setupFilters();renderProducts();renderProductPage();setupReturnPolicy();
